export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const SEARCH_MOVIE_FAILED = "SEARCH_MOVIE_FAILED";

export const SEARCH_MOVIE_DETAILS = "SEARCH_MOVIE_DETAILS";
export const SEARCH_MOVIE_DETAILS_SUCCESS = "SEARCH_MOVIE_DETAILS_SUCCESS";
export const SEARCH_MOVIE_DETAILS_FAILED = "SEARCH_MOVIE_DETAILS_FAILED";
